application: lookingforbirra
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.5"

env_variables:
  DJANGO_SETTINGS_MODULE: 'lookingforbirra.settings'

builtins:
- django_wsgi: on
